# -*- coding: utf-8 -*-
"""Big Data Analytics of E-Commerce Customer Behaviour

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jz-NnPUq64LhqVlD0tJckQsayzLi-RHs
"""

# ============================================================
# IST3134 BIG DATA ANALYTICS IN THE CLOUD
# GROUP ASSIGNMENT
#
# PANDAS PERFORMANCE BENCHMARK - GOOGLE COLAB
#
# Dataset:
# 2019-Nov.csv
#
# THREE ANALYTICAL OPERATIONS:
# 1. Event Distribution
# 2. Daily Purchase and Revenue Analysis
# 3. Top 10 Brands by Estimated Revenue
#
# FOUR PERFORMANCE EVALUATIONS:
# 1. Execution Time
# 2. Scalability
# 3. Memory Requirements / Limitations
# 4. Ability to Handle Increasing Data Volumes
# ============================================================


# ============================================================
# 1. IMPORT LIBRARIES
# ============================================================

from google.colab import drive

import pandas as pd
import matplotlib.pyplot as plt
import time
import os
import gc
import psutil
import glob


# ============================================================
# 2. MOUNT GOOGLE DRIVE
# ============================================================

drive.mount("/content/drive")


# ============================================================
# 3. LOCATE DATASET
# ============================================================

# If the file is directly inside My Drive:
FILE_PATH = "/content/drive/MyDrive/2019-Nov.csv"

# If it is NOT there, the code will try to find it
if not os.path.exists(FILE_PATH):

    print("2019-Nov.csv is not directly inside MyDrive.")
    print("Searching Google Drive...")

    possible_files = glob.glob(
        "/content/drive/MyDrive/**/2019-Nov.csv",
        recursive=True
    )

    if len(possible_files) == 0:
        raise FileNotFoundError(
            "\n2019-Nov.csv could not be found in Google Drive.\n"
            "Check that the file has finished downloading/uploading."
        )

    FILE_PATH = possible_files[0]


# ============================================================
# 4. OUTPUT FOLDER
# ============================================================

OUTPUT_FOLDER = (
    "/content/drive/MyDrive/"
    "IST3134_Pandas_Benchmark_Results"
)

os.makedirs(
    OUTPUT_FOLDER,
    exist_ok=True
)


# ============================================================
# 5. CHECK DATASET
# ============================================================

print("\n")
print("=" * 70)
print("DATASET CHECK")
print("=" * 70)

file_size_gb = (
    os.path.getsize(FILE_PATH)
    / (1024 ** 3)
)

print("Dataset found successfully.")
print(f"Path      : {FILE_PATH}")
print(f"File size : {file_size_gb:.2f} GB")


# ============================================================
# 6. EXPECTED COLUMNS
# ============================================================

EXPECTED_COLUMNS = [

    "event_time",
    "event_type",
    "product_id",
    "category_id",
    "category_code",
    "brand",
    "price",
    "user_id",
    "user_session"

]


# ============================================================
# 7. DATA TYPES
# ============================================================

# Nullable Int64 is used so the code will not fail
# if an ID column contains a missing value.

DTYPES = {

    "event_time": "string",

    "event_type": "string",

    "product_id": "Int64",

    "category_id": "Int64",

    "category_code": "string",

    "brand": "string",

    "price": "float64",

    "user_id": "Int64",

    "user_session": "string"

}


# ============================================================
# 8. SAMPLE SIZES
# ============================================================

# IMPORTANT:
# These must also be used for the AWS Spark scalability test.

SAMPLE_SIZES = [

    100_000,
    500_000,
    1_000_000,
    5_000_000

]


# ============================================================
# 9. MEMORY FUNCTIONS
# ============================================================

def get_process_memory_mb():

    process = psutil.Process(
        os.getpid()
    )

    return (
        process.memory_info().rss
        / (1024 ** 2)
    )


def get_available_memory_mb():

    return (
        psutil.virtual_memory().available
        / (1024 ** 2)
    )


# ============================================================
# 10. OPERATION 1
# EVENT DISTRIBUTION
# ============================================================

def event_distribution(df):

    result = (

        df
        .groupby(
            "event_type",
            dropna=False
        )
        .size()
        .reset_index(
            name="event_count"
        )

    )


    total_events = len(df)


    result["percentage"] = (

        result["event_count"]
        / total_events
        * 100

    ).round(2)


    result = (

        result
        .sort_values(
            "event_count",
            ascending=False
        )
        .reset_index(
            drop=True
        )

    )


    return result


# ============================================================
# 11. OPERATION 2
# DAILY PURCHASE AND REVENUE ANALYSIS
# ============================================================

def daily_purchase_revenue(df):

    # Select purchase events
    purchases = (

        df.loc[
            df["event_type"] == "purchase",
            [
                "event_time",
                "event_type",
                "price"
            ]
        ]
        .copy()

    )


    # Extract YYYY-MM-DD from event_time
    purchases["event_date"] = (

        purchases["event_time"]
        .str.slice(
            0,
            10
        )

    )


    # Invalid prices are excluded from
    # revenue and average calculations.
    # Purchase-event count still counts
    # all purchase events.

    purchases["valid_price"] = (

        purchases["price"]
        .where(

            purchases["price"].notna()
            &
            (purchases["price"] > 0)

        )

    )


    result = (

        purchases
        .groupby(
            "event_date"
        )
        .agg(

            num_purchase_events=(
                "event_type",
                "size"
            ),

            estimated_revenue=(
                "valid_price",
                "sum"
            ),

            avg_purchase_event_value=(
                "valid_price",
                "mean"
            )

        )
        .reset_index()
        .sort_values(
            "event_date"
        )

    )


    result["estimated_revenue"] = (

        result[
            "estimated_revenue"
        ].round(2)

    )


    result[
        "avg_purchase_event_value"
    ] = (

        result[
            "avg_purchase_event_value"
        ].round(2)

    )


    return result


# ============================================================
# 12. OPERATION 3
# TOP 10 BRANDS BY ESTIMATED REVENUE
# ============================================================

def top10_brands(df):

    # Select purchase events
    purchases = (

        df.loc[
            df["event_type"] == "purchase",
            [
                "brand",
                "price"
            ]
        ]
        .copy()

    )


    # Remove missing / blank brands
    purchases = (

        purchases.loc[

            purchases["brand"].notna()
            &
            (
                purchases["brand"]
                .str.strip()
                != ""
            )

        ]
        .copy()

    )


    # Invalid price values are ignored
    # for revenue and average calculations.

    purchases["valid_price"] = (

        purchases["price"]
        .where(

            purchases["price"].notna()
            &
            (purchases["price"] > 0)

        )

    )


    result = (

        purchases

        .groupby(
            "brand"
        )

        .agg(

            estimated_revenue=(
                "valid_price",
                "sum"
            ),

            num_purchase_events=(
                "brand",
                "size"
            ),

            avg_purchase_event_value=(
                "valid_price",
                "mean"
            )

        )

        .reset_index()

    )


    result[
        "estimated_revenue"
    ] = (

        result[
            "estimated_revenue"
        ].round(2)

    )


    result[
        "avg_purchase_event_value"
    ] = (

        result[
            "avg_purchase_event_value"
        ].round(2)

    )


    result = (

        result

        .sort_values(
            "estimated_revenue",
            ascending=False
        )

        .head(10)

        .reset_index(
            drop=True
        )

    )


    return result


# ============================================================
# 13. STORAGE FOR PERFORMANCE RESULTS
# ============================================================

performance_results = []


# Store analytical results from
# the largest successfully completed sample.

largest_event_result = None
largest_daily_result = None
largest_brand_result = None

largest_completed_rows = 0


# ============================================================
# 14. START BENCHMARK
# ============================================================

for requested_rows in SAMPLE_SIZES:

    print("\n")
    print("=" * 70)

    print(
        f"TESTING {requested_rows:,} ROWS"
    )

    print("=" * 70)


    df = None


    try:

        # ====================================================
        # MEMORY BEFORE LOADING
        # ====================================================

        gc.collect()


        process_memory_before = (
            get_process_memory_mb()
        )


        available_memory_before = (
            get_available_memory_mb()
        )


        # ====================================================
        # LOAD SAMPLE
        # ====================================================

        load_start = (
            time.perf_counter()
        )


        df = pd.read_csv(

            FILE_PATH,

            nrows=requested_rows,

            dtype=DTYPES

        )


        load_time = (

            time.perf_counter()
            - load_start

        )


        actual_rows = len(df)


        # ====================================================
        # VERIFY COLUMNS
        # ====================================================

        missing_columns = [

            column

            for column
            in EXPECTED_COLUMNS

            if column
            not in df.columns

        ]


        if missing_columns:

            raise ValueError(

                "Missing expected columns: "
                + str(missing_columns)

            )


        # ====================================================
        # MEMORY AFTER LOADING
        # ====================================================

        dataframe_memory_mb = (

            df.memory_usage(
                index=True,
                deep=True
            )
            .sum()

            / (1024 ** 2)

        )


        process_memory_after_load = (
            get_process_memory_mb()
        )


        available_memory_after_load = (
            get_available_memory_mb()
        )


        print(
            f"Requested rows       : "
            f"{requested_rows:,}"
        )

        print(
            f"Actual rows loaded   : "
            f"{actual_rows:,}"
        )

        print(
            f"Load time            : "
            f"{load_time:.4f} seconds"
        )

        print(
            f"DataFrame memory     : "
            f"{dataframe_memory_mb:.2f} MB"
        )

        print(
            f"Python process RAM   : "
            f"{process_memory_after_load:.2f} MB"
        )

        print(
            f"Available system RAM : "
            f"{available_memory_after_load:.2f} MB"
        )


        # ====================================================
        # OPERATION 1
        # EVENT DISTRIBUTION
        # ====================================================

        print("\n")
        print("-" * 70)
        print("OPERATION 1: EVENT DISTRIBUTION")
        print("-" * 70)


        start = (
            time.perf_counter()
        )


        event_result = (
            event_distribution(df)
        )


        event_time = (

            time.perf_counter()
            - start

        )


        print(
            event_result.to_string(
                index=False
            )
        )


        print(
            f"\nExecution time: "
            f"{event_time:.4f} seconds"
        )


        memory_after_event = (
            get_process_memory_mb()
        )


        # ====================================================
        # OPERATION 2
        # DAILY PURCHASE & REVENUE
        # ====================================================

        print("\n")
        print("-" * 70)

        print(
            "OPERATION 2: DAILY PURCHASE "
            "AND REVENUE ANALYSIS"
        )

        print("-" * 70)


        start = (
            time.perf_counter()
        )


        daily_result = (
            daily_purchase_revenue(df)
        )


        daily_time = (

            time.perf_counter()
            - start

        )


        print(
            daily_result.to_string(
                index=False
            )
        )


        print(
            f"\nExecution time: "
            f"{daily_time:.4f} seconds"
        )


        memory_after_daily = (
            get_process_memory_mb()
        )


        # ====================================================
        # OPERATION 3
        # TOP 10 BRANDS
        # ====================================================

        print("\n")
        print("-" * 70)

        print(
            "OPERATION 3: TOP 10 BRANDS "
            "BY ESTIMATED REVENUE"
        )

        print("-" * 70)


        start = (
            time.perf_counter()
        )


        brand_result = (
            top10_brands(df)
        )


        brand_time = (

            time.perf_counter()
            - start

        )


        print(
            brand_result.to_string(
                index=False
            )
        )


        print(
            f"\nExecution time: "
            f"{brand_time:.4f} seconds"
        )


        memory_after_brand = (
            get_process_memory_mb()
        )


        # ====================================================
        # TOTAL ANALYTICAL TIME
        # ====================================================

        total_analysis_time = (

            event_time
            +
            daily_time
            +
            brand_time

        )


        # ====================================================
        # MAXIMUM OBSERVED PROCESS MEMORY
        # ====================================================

        max_process_memory = max(

            process_memory_after_load,
            memory_after_event,
            memory_after_daily,
            memory_after_brand

        )


        # ====================================================
        # SAVE PERFORMANCE RESULT
        # ====================================================

        performance_results.append({

            "rows":
                actual_rows,

            "load_time_sec":
                round(
                    load_time,
                    4
                ),

            "event_distribution_sec":
                round(
                    event_time,
                    4
                ),

            "daily_purchase_revenue_sec":
                round(
                    daily_time,
                    4
                ),

            "top10_brands_sec":
                round(
                    brand_time,
                    4
                ),

            "total_analysis_time_sec":
                round(
                    total_analysis_time,
                    4
                ),

            "dataframe_memory_mb":
                round(
                    dataframe_memory_mb,
                    2
                ),

            "process_memory_before_mb":
                round(
                    process_memory_before,
                    2
                ),

            "process_memory_after_load_mb":
                round(
                    process_memory_after_load,
                    2
                ),

            "max_process_memory_mb":
                round(
                    max_process_memory,
                    2
                ),

            "available_memory_after_load_mb":
                round(
                    available_memory_after_load,
                    2
                ),

            "completed":
                True

        })


        # ====================================================
        # SAVE LARGEST SUCCESSFUL ANALYTICAL OUTPUT
        # ====================================================

        if actual_rows > largest_completed_rows:

            largest_completed_rows = (
                actual_rows
            )

            largest_event_result = (
                event_result.copy()
            )

            largest_daily_result = (
                daily_result.copy()
            )

            largest_brand_result = (
                brand_result.copy()
            )


        # ====================================================
        # PRINT SUMMARY
        # ====================================================

        print("\n")
        print("-" * 70)
        print("PERFORMANCE SUMMARY")
        print("-" * 70)


        print(
            f"Rows                     : "
            f"{actual_rows:,}"
        )

        print(
            f"Load time                : "
            f"{load_time:.4f} seconds"
        )

        print(
            f"Event Distribution       : "
            f"{event_time:.4f} seconds"
        )

        print(
            f"Daily Purchase & Revenue : "
            f"{daily_time:.4f} seconds"
        )

        print(
            f"Top 10 Brands            : "
            f"{brand_time:.4f} seconds"
        )

        print(
            f"Total analytical time    : "
            f"{total_analysis_time:.4f} seconds"
        )

        print(
            f"DataFrame memory         : "
            f"{dataframe_memory_mb:.2f} MB"
        )

        print(
            f"Maximum process RAM      : "
            f"{max_process_memory:.2f} MB"
        )

        print(
            "Status                   : SUCCESS"
        )


        # ====================================================
        # CLEAR MEMORY
        # ====================================================

        del event_result
        del daily_result
        del brand_result
        del df

        df = None

        gc.collect()

        time.sleep(2)


    # ========================================================
    # MEMORY ERROR
    # ========================================================

    except MemoryError:

        print("\n")
        print("=" * 70)
        print("MEMORY LIMIT REACHED")
        print("=" * 70)


        print(
            f"Pandas could not complete "
            f"the {requested_rows:,}-row test "
            f"because of insufficient memory."
        )


        performance_results.append({

            "rows":
                requested_rows,

            "load_time_sec":
                None,

            "event_distribution_sec":
                None,

            "daily_purchase_revenue_sec":
                None,

            "top10_brands_sec":
                None,

            "total_analysis_time_sec":
                None,

            "dataframe_memory_mb":
                None,

            "process_memory_before_mb":
                None,

            "process_memory_after_load_mb":
                None,

            "max_process_memory_mb":
                None,

            "available_memory_after_load_mb":
                None,

            "completed":
                False

        })


        if df is not None:

            del df


        gc.collect()

        break


    # ========================================================
    # OTHER ERROR
    # ========================================================

    except Exception as e:

        print("\n")
        print("=" * 70)
        print("ERROR")
        print("=" * 70)


        print(
            f"Error type: "
            f"{type(e).__name__}"
        )


        print(
            f"Message: {e}"
        )


        print(
            "\nThis error is NOT counted as "
            "a Pandas performance limitation."
        )


        if df is not None:

            del df


        gc.collect()

        raise


# ============================================================
# 15. FINAL PERFORMANCE TABLE
# ============================================================

performance_df = pd.DataFrame(
    performance_results
)


print("\n")
print("=" * 70)
print("FINAL PANDAS PERFORMANCE RESULTS")
print("=" * 70)


display(
    performance_df
)


# ============================================================
# 16. SAVE PERFORMANCE RESULTS
# ============================================================

performance_file = os.path.join(

    OUTPUT_FOLDER,

    "pandas_performance_results.csv"

)


performance_df.to_csv(

    performance_file,

    index=False

)


print("\nPerformance table saved to:")
print(performance_file)


# ============================================================
# 17. SAVE LARGEST SAMPLE ANALYTICAL OUTPUTS
# ============================================================

if largest_event_result is not None:

    largest_event_result.to_csv(

        os.path.join(
            OUTPUT_FOLDER,
            "event_distribution_largest_sample.csv"
        ),

        index=False

    )


if largest_daily_result is not None:

    largest_daily_result.to_csv(

        os.path.join(
            OUTPUT_FOLDER,
            "daily_purchase_revenue_largest_sample.csv"
        ),

        index=False

    )


if largest_brand_result is not None:

    largest_brand_result.to_csv(

        os.path.join(
            OUTPUT_FOLDER,
            "top10_brands_largest_sample.csv"
        ),

        index=False

    )


# ============================================================
# 18. SUCCESSFUL BENCHMARKS ONLY
# ============================================================

successful_df = (

    performance_df[
        performance_df["completed"] == True
    ]
    .copy()

)


# ============================================================
# 19. SCALABILITY / EXECUTION TIME GRAPH
# ============================================================

if len(successful_df) > 0:

    plt.figure(
        figsize=(10, 6)
    )


    plt.plot(

        successful_df["rows"],

        successful_df[
            "event_distribution_sec"
        ],

        marker="o",

        label="Event Distribution"

    )


    plt.plot(

        successful_df["rows"],

        successful_df[
            "daily_purchase_revenue_sec"
        ],

        marker="o",

        label="Daily Purchase & Revenue"

    )


    plt.plot(

        successful_df["rows"],

        successful_df[
            "top10_brands_sec"
        ],

        marker="o",

        label="Top 10 Brands"

    )


    plt.xlabel(
        "Number of Records"
    )

    plt.ylabel(
        "Execution Time (Seconds)"
    )

    plt.title(
        "Pandas Execution Time by Dataset Size"
    )

    plt.legend()

    plt.grid(True)

    plt.tight_layout()


    scalability_file = os.path.join(

        OUTPUT_FOLDER,

        "pandas_scalability.png"

    )


    plt.savefig(

        scalability_file,

        dpi=300,

        bbox_inches="tight"

    )


    plt.show()


# ============================================================
# 20. MEMORY USAGE GRAPH
# ============================================================

if len(successful_df) > 0:

    plt.figure(
        figsize=(10, 6)
    )


    plt.plot(

        successful_df["rows"],

        successful_df[
            "dataframe_memory_mb"
        ],

        marker="o"

    )


    plt.xlabel(
        "Number of Records"
    )

    plt.ylabel(
        "DataFrame Memory Usage (MB)"
    )

    plt.title(
        "Pandas Memory Usage by Dataset Size"
    )

    plt.grid(True)

    plt.tight_layout()


    memory_file = os.path.join(

        OUTPUT_FOLDER,

        "pandas_memory_usage.png"

    )


    plt.savefig(

        memory_file,

        dpi=300,

        bbox_inches="tight"

    )


    plt.show()


# ============================================================
# 21. LARGE-VOLUME HANDLING
# ============================================================

print("\n")
print("=" * 70)
print("LARGE-VOLUME HANDLING")
print("=" * 70)


if len(successful_df) > 0:

    largest_successful = int(

        successful_df[
            "rows"
        ].max()

    )


    print(
        "Largest dataset successfully tested "
        "with Pandas:"
    )

    print(
        f"{largest_successful:,} records"
    )


    if (
        largest_successful
        == max(SAMPLE_SIZES)
    ):

        print(
            "\nAll planned Pandas benchmark "
            "sizes were completed successfully."
        )

    else:

        print(
            "\nPandas did not complete all "
            "planned benchmark sizes."
        )


else:

    print(
        "No benchmark size was completed."
    )


# ============================================================
# 22. FOUR PERFORMANCE CRITERIA SUMMARY
# ============================================================

print("\n")
print("=" * 70)
print("FOUR PERFORMANCE EVALUATION CRITERIA")
print("=" * 70)


print(
    "\n1. EXECUTION TIME"
)

print(
    "Use event_distribution_sec, "
    "daily_purchase_revenue_sec and "
    "top10_brands_sec."
)


print(
    "\n2. SCALABILITY"
)

print(
    "Compare how execution time changes "
    "from 100K to 500K to 1M to 5M rows."
)


print(
    "\n3. MEMORY REQUIREMENTS / LIMITATIONS"
)

print(
    "Use dataframe_memory_mb and "
    "max_process_memory_mb."
)


print(
    "\n4. ABILITY TO HANDLE LARGE DATA VOLUMES"
)

print(
    "Use the largest successfully tested "
    "number of records."
)


# ============================================================
# 23. SAVED OUTPUT FILES
# ============================================================

print("\n")
print("=" * 70)
print("SAVED RESULTS")
print("=" * 70)


for filename in os.listdir(
    OUTPUT_FOLDER
):

    print(

        os.path.join(
            OUTPUT_FOLDER,
            filename
        )

    )


print("\nBenchmark completed successfully.")